# (PART) EXPLORATORY ANALYSIS {-}

# Data Transformation and Visualization {#transform-and-visualize}

## Load libraries and data
```{r message=FALSE, warning=FALSE}
source("R/common.R")
library(tidyverse)

load("RDataRDS/Rjoined_objects.RData", verbose = T)
```

## Stacked barcharts using `ggplot2` package{#ggplot-bars}

```{r ggplot_barchart, fig.height=10, fig.width=10, animation.hook='gifski'}
df <- mo_Rjoined_object %>% 
  rename(group = isolate)

library(ggtext) # for markdown and rmarkdown formatting

taxon_rel_abund <- df %>% 
  filter(level == "phylum") %>% 
  group_by(sample_id, taxon, group) %>% 
  summarise(rel_abund = sum(rel_abund), .groups = "drop") %>% 
  group_by(group, taxon) %>% 
  summarise(mean_rel_abund = 100*mean(rel_abund), .groups = "drop") %>% 
  mutate(taxon = str_replace(taxon,
                             "(.*)_unclassified", "Unclassified *\\1*"),
         taxon = str_replace(taxon,
                             "^(\\S*)$", "*\\1*"))

taxon_rel_abund %>%
  ggplot(aes(x = group, y = mean_rel_abund, fill = taxon)) +
  geom_col() +
  scale_x_discrete(breaks = c("Buffalo",
                              "Warthog",
                              "Wildebeest",
                              "Zebra"),
                   labels = c("A",
                              "B",
                              "C",
                              "D")) +
  labs(x = NULL,
       y = "Mean Relative Abundance (%)",
       title = "Barchart before pooling taxa",
       fill = "Phylum") +
  theme_classic() +
  theme(axis.text.x = element_markdown(),
        legend.text = element_markdown(),
        legend.key.size = unit(8, "pt")) +
  guides(fill=guide_legend(ncol=1)) +
  scale_y_continuous(expand = c(0, 0)) + 
  centertitle

ggsave("figures/stacked_bar1.tiff", width = 5, height = 4)


### Pooling taxon by relative abundance {#pooled-barchart}

taxon_pool <- taxon_rel_abund %>%
  group_by(taxon) %>%
  summarise(pool = max(mean_rel_abund) < 3,
            mean = mean(mean_rel_abund),
            .groups = "drop")

inner_join(taxon_rel_abund, taxon_pool, by = "taxon" ) %>% 
  mutate(taxon = if_else(pool, "Other", taxon)) %>% 
  group_by(group, taxon) %>% 
  summarise(mean_rel_abund = sum(mean_rel_abund), .groups = "drop") %>% 
  ggplot(aes(x = group, y = mean_rel_abund, fill = taxon)) +
  geom_col() +
  scale_x_discrete(breaks = c("Buffalo",
                              "Warthog",
                              "Wildebeest",
                              "Zebra"),
                   labels = c("A",
                              "B",
                              "C",
                              "D")) +
  labs(x = NULL,
       y = "Mean Relative Abundance (%)",
       title = "Barchart with pooled taxa",       
       fill = "Phylum") +
  theme_classic() +
  theme(axis.text.x = element_markdown(),
        legend.text = element_markdown(),
        legend.key.size = unit(8, "pt")) +
  guides(fill=guide_legend(ncol=1)) +
  scale_y_continuous(expand = c(0, 0)) + 
  centertitle

ggsave("figures/stacked_bar2.tiff", width = 5, height = 4)


### Reordering using `forcat` package {#reordered-barchart}

library(forcats)

inner_join(taxon_rel_abund, taxon_pool, by = "taxon" ) %>% 
  mutate(taxon = if_else(pool, "Other", taxon)) %>% 
  group_by(group, taxon) %>% 
  summarise(mean_rel_abund = sum(mean_rel_abund), 
            mean = min(mean),
            .groups = "drop") %>%
  mutate(taxon = factor(taxon),
         taxon = fct_reorder(taxon, mean, .desc = T),
         taxon = fct_shift(taxon, n = 1)) %>%
  # pull(taxon) %>% 
  # levels() %>% 
  ggplot(aes(x = group, y = mean_rel_abund, fill = taxon)) +
  geom_col() +
  scale_x_discrete(breaks = c("Buffalo",
                              "Warthog",
                              "Wildebeest",
                              "Zebra"),
                   labels = c("A",
                              "B",
                              "C",
                              "D")) +
  labs(x = NULL,
       y = "Mean Relative Abundance (%)",
       title = "Barchart reordered using `forcats` package",
       fill = "Phylum") +
  theme_classic() +
  theme(axis.text.x = element_markdown(),
        legend.text = element_markdown(),
        legend.key.size = unit(8, "pt")) +
  guides(fill=guide_legend(ncol=1))+
  scale_y_continuous(expand = c(0, 0)) + 
  centertitle

ggsave("figures/stacked_bar3.tiff", width = 5, height = 4)


### Reordering manually

library(forcats)
library(RColorBrewer)

inner_join(taxon_rel_abund, taxon_pool, by = "taxon" ) %>% 
  mutate(taxon = if_else(pool, "Other", taxon)) %>% 
  group_by(group, taxon) %>% 
  summarise(mean_rel_abund = sum(mean_rel_abund), 
            mean = min(mean),
            .groups = "drop") %>%
  mutate(taxon = factor(taxon),
         taxon = fct_reorder(taxon, mean, .desc = T),
         taxon = fct_shift(taxon, n = 1)) %>%
  ggplot(aes(x = group, y = mean_rel_abund, fill = taxon)) +
  geom_col() +
  scale_fill_manual(name = NULL,
                    breaks = c("*Firmicutes*", "*Proteobacteria*", "*Bacteroidota*", "Unclassified *Bacteria*", "Other"),
                    # values = c(brewer.pal(n = 4, "Dark2"), "gray")) +
                    values = c(brewer.pal(n = 4, "Dark2"), "gray")) +
  scale_x_discrete(breaks = c("Buffalo",
                              "Warthog",
                              "Wildebeest",
                              "Zebra"),
                   labels = c("A",
                              "B",
                              "C",
                              "D")) +
  labs(x = NULL,
       y = "Mean Relative Abundance (%)",
       title = "Barcharts reordered manually",
       fill = "Phylum") +
  theme_classic() +
  theme(axis.text.x = element_markdown(),
        legend.text = element_markdown(),
        legend.key.size = unit(8, "pt")) +
  guides(fill=guide_legend(ncol=1)) +
  scale_y_continuous(expand = c(0, 0)) + 
  centertitle

ggsave("figures/stacked_bar4.tiff", width = 5, height = 4)

```



## Stacked barcharts using phyloseq package {#phyloseq-bars}

```{r phyloseq_barchart, fig.height=10, fig.width=10, animation.hook='gifski'}
library(phyloseq)

ps_rel <- ps_m3_rel

# Kingdom
phyloseq::plot_bar(ps_rel, fill = "kingdom") +
  geom_bar(aes(color = kingdom, fill = kingdom), stat = "identity", position = "stack") +
  labs(x = "", y = "Relative Abundance\n") +
  facet_wrap(~ platform, scales = "free") +
  theme(panel.background = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  # nolegend +
  labs(title = "Kingdom abundance") + 
  centertitle +
  nolegend

# phylum
phyloseq::plot_bar(ps_rel, fill = "phylum") +
  geom_bar(aes(color = phylum, fill = phylum), stat = "identity", position = "stack") +
  labs(x = "", y = "Relative Abundance\n") +
  facet_wrap(~ platform, scales = "free") +
  theme(panel.background = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  #nolegend +
  labs(title = "Phylum abundance") + 
  centertitle +
  nolegend

# class
phyloseq::plot_bar(ps_rel, fill = "class") +
  geom_bar(aes(color = class, fill = class), stat = "identity", position = "stack") +
  labs(x = "", y = "Relative Abundance\n") +
  facet_wrap(~ platform, scales = "free") +
  theme(panel.background = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  # nolegend +
  labs(title = "Class abundance") + 
  centertitle +
  nolegend

# order
phyloseq::plot_bar(ps_rel, fill = "order") +
  geom_bar(aes(color = order, fill = order), stat = "identity", position = "stack") +
  labs(x = "", y = "Relative Abundance\n") +
  facet_wrap(~ platform, scales = "free") +
  theme(panel.background = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  # nolegend +
  labs(title = "Order abundance") + 
  centertitle +
  nolegend

# family    
phyloseq::plot_bar(ps_rel, fill = "family") +
  geom_bar(aes(color = family, fill = family), stat = "identity", position = "stack") +
  labs(x = "", y = "Relative Abundance\n") +
  facet_wrap(~ platform, scales = "free") +
  theme(panel.background = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  # nolegend +
  labs(title = "Family abundance") + 
  centertitle +
  nolegend

# genus   
phyloseq::plot_bar(ps_rel, fill = "genus") +
  geom_bar(aes(color = genus, fill = genus), stat = "identity", position = "stack") +
  labs(x = "", y = "Relative Abundance\n") +
  facet_wrap(~ platform, scales = "free") +
  theme(panel.background = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  # nolegend +
  labs(title = "Genus abundance") + 
  centertitle +
  nolegend
```